//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPMobileAdmin.VPCoreService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VPMobileAVLSettings", Namespace="http://schemas.datacontract.org/2004/07/VPCoreService")]
    [System.SerializableAttribute()]
    public partial class VPMobileAVLSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AVLIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ConfigIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfigNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VPMobileAdmin.VPCoreService.VPAVLGroupInfo[] GroupsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AVLID {
            get {
                return this.AVLIDField;
            }
            set {
                if ((this.AVLIDField.Equals(value) != true)) {
                    this.AVLIDField = value;
                    this.RaisePropertyChanged("AVLID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ConfigID {
            get {
                return this.ConfigIDField;
            }
            set {
                if ((this.ConfigIDField.Equals(value) != true)) {
                    this.ConfigIDField = value;
                    this.RaisePropertyChanged("ConfigID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfigName {
            get {
                return this.ConfigNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigNameField, value) != true)) {
                    this.ConfigNameField = value;
                    this.RaisePropertyChanged("ConfigName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VPMobileAdmin.VPCoreService.VPAVLGroupInfo[] Groups {
            get {
                return this.GroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupsField, value) != true)) {
                    this.GroupsField = value;
                    this.RaisePropertyChanged("Groups");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VPAVLGroupInfo", Namespace="http://schemas.datacontract.org/2004/07/VPCoreService")]
    [System.SerializableAttribute()]
    public partial class VPAVLGroupInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupSymbolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupColor {
            get {
                return this.GroupColorField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupColorField, value) != true)) {
                    this.GroupColorField = value;
                    this.RaisePropertyChanged("GroupColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupSymbol {
            get {
                return this.GroupSymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupSymbolField, value) != true)) {
                    this.GroupSymbolField = value;
                    this.RaisePropertyChanged("GroupSymbol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VPMobileDispatchSettings", Namespace="http://schemas.datacontract.org/2004/07/VPCoreService")]
    [System.SerializableAttribute()]
    public partial class VPMobileDispatchSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ConfigIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfigNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultE911CallSymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultIncidentSymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DispatchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid E911SourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncidentSourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VPMobileAdmin.VPCoreService.VPDispatchIncidentTypeSettings[] IncidentTypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ConfigID {
            get {
                return this.ConfigIDField;
            }
            set {
                if ((this.ConfigIDField.Equals(value) != true)) {
                    this.ConfigIDField = value;
                    this.RaisePropertyChanged("ConfigID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfigName {
            get {
                return this.ConfigNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigNameField, value) != true)) {
                    this.ConfigNameField = value;
                    this.RaisePropertyChanged("ConfigName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultE911CallSymbol {
            get {
                return this.DefaultE911CallSymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultE911CallSymbolField, value) != true)) {
                    this.DefaultE911CallSymbolField = value;
                    this.RaisePropertyChanged("DefaultE911CallSymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultIncidentSymbol {
            get {
                return this.DefaultIncidentSymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultIncidentSymbolField, value) != true)) {
                    this.DefaultIncidentSymbolField = value;
                    this.RaisePropertyChanged("DefaultIncidentSymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DispatchID {
            get {
                return this.DispatchIDField;
            }
            set {
                if ((this.DispatchIDField.Equals(value) != true)) {
                    this.DispatchIDField = value;
                    this.RaisePropertyChanged("DispatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid E911SourceID {
            get {
                return this.E911SourceIDField;
            }
            set {
                if ((this.E911SourceIDField.Equals(value) != true)) {
                    this.E911SourceIDField = value;
                    this.RaisePropertyChanged("E911SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncidentSourceID {
            get {
                return this.IncidentSourceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.IncidentSourceIDField, value) != true)) {
                    this.IncidentSourceIDField = value;
                    this.RaisePropertyChanged("IncidentSourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VPMobileAdmin.VPCoreService.VPDispatchIncidentTypeSettings[] IncidentTypes {
            get {
                return this.IncidentTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.IncidentTypesField, value) != true)) {
                    this.IncidentTypesField = value;
                    this.RaisePropertyChanged("IncidentTypes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VPDispatchIncidentTypeSettings", Namespace="http://schemas.datacontract.org/2004/07/VPCoreService")]
    [System.SerializableAttribute()]
    public partial class VPDispatchIncidentTypeSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncidentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncidentType {
            get {
                return this.IncidentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IncidentTypeField, value) != true)) {
                    this.IncidentTypeField = value;
                    this.RaisePropertyChanged("IncidentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VPCoreService.IVPMService")]
    public interface IVPMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetAvailableAvlSettings", ReplyAction="http://tempuri.org/IVPMService/GetAvailableAvlSettingsResponse")]
        VPMobileAdmin.VPCoreService.VPMobileAVLSettings[] GetAvailableAvlSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetAvlSettings", ReplyAction="http://tempuri.org/IVPMService/GetAvlSettingsResponse")]
        VPMobileAdmin.VPCoreService.VPMobileAVLSettings GetAvlSettings(System.Guid avlId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetAvailableDispatchSettings", ReplyAction="http://tempuri.org/IVPMService/GetAvailableDispatchSettingsResponse")]
        VPMobileAdmin.VPCoreService.VPMobileDispatchSettings[] GetAvailableDispatchSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetDispatchSettings", ReplyAction="http://tempuri.org/IVPMService/GetDispatchSettingsResponse")]
        VPMobileAdmin.VPCoreService.VPMobileDispatchSettings GetDispatchSettings(System.Guid dispatchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetDispatchRecordData", ReplyAction="http://tempuri.org/IVPMService/GetDispatchRecordDataResponse")]
        System.Collections.Generic.Dictionary<string, object>[] GetDispatchRecordData(string strID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetAVLLastReportRecordData", ReplyAction="http://tempuri.org/IVPMService/GetAVLLastReportRecordDataResponse")]
        System.Collections.Generic.Dictionary<string, object>[] GetAVLLastReportRecordData(string strID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetAvailableAvlSettings2", ReplyAction="http://tempuri.org/IVPMService/GetAvailableAvlSettings2Response")]
        VPMobileAdmin.VPCoreService.VPMobileAVLSettings[] GetAvailableAvlSettings2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetAvlSettings2", ReplyAction="http://tempuri.org/IVPMService/GetAvlSettings2Response")]
        VPMobileAdmin.VPCoreService.VPMobileAVLSettings GetAvlSettings2(System.Guid avlId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetAvailableDispatchSettings2", ReplyAction="http://tempuri.org/IVPMService/GetAvailableDispatchSettings2Response")]
        VPMobileAdmin.VPCoreService.VPMobileDispatchSettings[] GetAvailableDispatchSettings2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetDispatchSettings2", ReplyAction="http://tempuri.org/IVPMService/GetDispatchSettings2Response")]
        VPMobileAdmin.VPCoreService.VPMobileDispatchSettings GetDispatchSettings2(System.Guid dispatchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetDispatchRecordData2", ReplyAction="http://tempuri.org/IVPMService/GetDispatchRecordData2Response")]
        System.Collections.Generic.Dictionary<string, object>[] GetDispatchRecordData2(string strID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPMService/GetAVLLastReportRecordData2", ReplyAction="http://tempuri.org/IVPMService/GetAVLLastReportRecordData2Response")]
        System.Collections.Generic.Dictionary<string, object>[] GetAVLLastReportRecordData2(string strID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVPMServiceChannel : VPMobileAdmin.VPCoreService.IVPMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VPMServiceClient : System.ServiceModel.ClientBase<VPMobileAdmin.VPCoreService.IVPMService>, VPMobileAdmin.VPCoreService.IVPMService {
        
        public VPMServiceClient() {
        }
        
        public VPMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VPMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VPMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VPMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VPMobileAdmin.VPCoreService.VPMobileAVLSettings[] GetAvailableAvlSettings() {
            return base.Channel.GetAvailableAvlSettings();
        }
        
        public VPMobileAdmin.VPCoreService.VPMobileAVLSettings GetAvlSettings(System.Guid avlId) {
            return base.Channel.GetAvlSettings(avlId);
        }
        
        public VPMobileAdmin.VPCoreService.VPMobileDispatchSettings[] GetAvailableDispatchSettings() {
            return base.Channel.GetAvailableDispatchSettings();
        }
        
        public VPMobileAdmin.VPCoreService.VPMobileDispatchSettings GetDispatchSettings(System.Guid dispatchId) {
            return base.Channel.GetDispatchSettings(dispatchId);
        }
        
        public System.Collections.Generic.Dictionary<string, object>[] GetDispatchRecordData(string strID) {
            return base.Channel.GetDispatchRecordData(strID);
        }
        
        public System.Collections.Generic.Dictionary<string, object>[] GetAVLLastReportRecordData(string strID) {
            return base.Channel.GetAVLLastReportRecordData(strID);
        }
        
        public VPMobileAdmin.VPCoreService.VPMobileAVLSettings[] GetAvailableAvlSettings2() {
            return base.Channel.GetAvailableAvlSettings2();
        }
        
        public VPMobileAdmin.VPCoreService.VPMobileAVLSettings GetAvlSettings2(System.Guid avlId) {
            return base.Channel.GetAvlSettings2(avlId);
        }
        
        public VPMobileAdmin.VPCoreService.VPMobileDispatchSettings[] GetAvailableDispatchSettings2() {
            return base.Channel.GetAvailableDispatchSettings2();
        }
        
        public VPMobileAdmin.VPCoreService.VPMobileDispatchSettings GetDispatchSettings2(System.Guid dispatchId) {
            return base.Channel.GetDispatchSettings2(dispatchId);
        }
        
        public System.Collections.Generic.Dictionary<string, object>[] GetDispatchRecordData2(string strID) {
            return base.Channel.GetDispatchRecordData2(strID);
        }
        
        public System.Collections.Generic.Dictionary<string, object>[] GetAVLLastReportRecordData2(string strID) {
            return base.Channel.GetAVLLastReportRecordData2(strID);
        }
    }
}
